[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
solc_version = "0.8.29"
via_ir = true
remappings = [
  "forge-std/=node_modules/forge-std/src/",
  "ds-test/=node_modules/ds-test/src/",
  "solidity-stringutils/=node_modules/solidity-stringutils/",
]

[fmt]
line_length = 80
tab_width = 2
bracket_spacing = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
